### ISSUE TITLE
how to link a file from Github

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/qvis#12]
I uploaded a trace to Github in https://github.com/lucas-clemente/quic-go/issues/2521. Unfortunately, Github doesn't allow me to upload a .qlog file, so I had to rename it to .qlog.txt.
Now qvis refuses to read it:

> Error: Trace had an error: {"qlog_version":"draft-01","description":"Generated 5/4/2020, 5:18:05 AM","traces":[{"error_description":"tshark:TransformToJSON : error : Error: Command failed: /wireshark/run/tshark --no-duplicate-keys -r /srv/qvis-cache/inputs/yev8bcvl9jsqphvm0cavdq/3iw6px6qek5so5bdqe1gff.txt -T json  > /srv/qvis-cache/inputs/yev8bcvl9jsqphvm0cavdq/52tzqk7t823xuzl9osyzd.json\nRunning as user \"root\" and group \"root\". This could be dangerous.\ntshark: The file \"/srv/qvis-cache/inputs/yev8bcvl9jsqphvm0cavdq/3iw6px6qek5so5bdqe1gff.txt\" isn't a capture file in a format TShark understands.

**Comment by rmarx** [comment]
To get around CORS, the qvis server downloads the qlog files and then sends them back to the qvis frontend. The qvis server is stupid and only takes files with ".qlog" on the back of the URL as qlogs, thinks the rest are pcaps. 

The easy fix is to add a query parameter to the URL, e.g., saying ?ext=.qlog. Then you trick the server and all is well...

For your example, that would be: 
https://qvis.edm.uhasselt.be/#/sequence?file=https://github.com/lucas-clemente/quic-go/files/4572857/log_2020-05-02T06-33-19.390504046UTC_server_fa99ffa2d66bd0d5b062.qlog.txt?ext=.qlog

Not entirely optimal, but if I have to write a heuristic parser to see if any file I download is valid qlog or not... though I agree that would probably be the cleaner option. Somewhere down the road maybe :)
