### ISSUE TITLE
Bug in live version

### ISSUE THREAD

**Issue by agrover** [quiclog/qvis#17]
**Describe the bug**
Uploading a file with the same file name as the previous file loaded (but different contents) does not load the new contents.

**Comment by rmarx** [comment]
Hello Andy,

Thanks for the bug report, but I am having problems reproducing it... 

My attempt: 
1. make a copy of an existing file into a new subdir (same filename) 
2. only change the name of the first event in the copied file (from `connection_started` to `connection_started2`) and nothing else
3. load the original file via file upload in qvis
4. load the changed file via file upload in qvis
5. in the sequence diagram, both are visible in the dropdown. Selecting either will show the appropriate file with the different event names.

Could you give me more info on your steps? Are you loading 2 different files via the same URL somehow maybe? Or are you using a different visualization than the sequence diagram (though that shouldn't matter in theory)? 

Thanks!

**Comment by agrover** [comment]
Hi, sorry for the delay in response. User confusion on my part.

> Are you loading 2 different files via the same URL somehow maybe? 

Yes, I'm working on adding more events, so I had a foo.qlog file, I displayed it in qvis, added some more events, re-ran a connection, and then re-uploaded (via "Option 2: Upload a file") the exact same filename that had been overwritten with new contents.

I was expecting reloading the same file would immediately replace the sequence with the new info, but qvis adds it to the dropdown but still shows the original data until the new trace is selected in the dropdown (which makes sense.)

So yeah, I get how things work a little better now, so I'm going to close this issue.
