### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by steschu77** [quiclog/qvis#2]
**Describe the bug**
Rendering a sequence diagram of the QLOG below causes an TypeError exception.

Note that the ACK-frame doesn't carry any additional information.

Example qlog:
```
{
    "qlog_version": "draft-00",
    "title": "Name of this particular qlog file (short)",
    "description": "Description for this group of traces (long)",
    "summary": {
    },
    "traces": [
        {
            "vantage_point": {
                "name": "backend-67",
                "type": "SERVER"
            },
            "title": "Name of this particular trace (short)",
            "description": "Description for this trace (long)",
            "event_fields": [
                "relative_time",
                "CATEGORY",
                "EVENT_TYPE",
                "DATA"
            ],
            "common_fields": {
                "protocol_type":  "QUIC_HTTP3"
            },            
            "events": [
[0, "TRANSPORT", "PACKET_SENT", { "packet_type": "initial", "header": { "packet_number": 0 }, "frames": [{ "frame_type": "crypto_hs"}, { "frame_type": "padding"}]}],
[5997, "TRANSPORT", "PACKET_RECEIVED", { "packet_type": "initial", "header": { "packet_number": 0 }, "frames": [{ "frame_type": "ack"}, { "frame_type": "crypto_hs"}]}]
            ]
        }
    ]
}
```

**Comment by rmarx** [comment]
Thanks for raising the issue @steschu77. Nice to see picoquic is considering qlog support :) Let me know if I can help more.

This issue should now be fixed on the live server as well. 

Side-note: there are some other mistakes in your qlog file:
- using relative_time ideally requires a reference_time in "common_fields"
- qlog doesn't have a frame type "crypto_hs", only "crypto"

Luckily, we do handle these gracefully in quicvis atm, so things don't crash, but you might not get fully correct behaviour.

**Comment by steschu77** [comment]
> using relative_time ideally requires a reference_time in "common_fields"
Done, but still having issues with client + server side times.

> qlog doesn't have a frame type "crypto_hs", only "crypto"
Fixed as well.

**Comment by steschu77** [comment]
This particular issue came up when I started converting to QLOG step by step and tested with only frame_type being set for frames. So I couldn't test with anything other than the attached file ;)
