### ISSUE TITLE
Not matching up send and receive

### ISSUE THREAD

**Issue by martinthomson** [quiclog/qvis#29]
The [attached qlog files](https://github.com/quiclog/qvis/files/5093370/7a1de67a86b189180d.zip) seem to display correctly, but not all of the events for sending are matched to receive events.

For instance, event 110 at the client is at packet_sent for "1RTT" packet "5".  Event 116 at the server is reported as packet_received for "1rtt" packet 5.  I originally thought this to be a bug in the log converter for picoquic, which produces lowercase names for 0RTT and 1RTT packets, but after fixing that the problem remains.  The input record is:

```json
[2446805, "transport", "packet_received", { "packet_type": "1RTT", "header": { "packet_size": 29, "packet_number": 5, "dcid": "46d3e6a2be3761fd", "quic_bit": 0 }, "frames": [{ 
    "frame_type": "ping"}]}],
```

However, the UI consistently shows the down-cased version, and adds a "type" field:

```json
Event nr: 116
[
  2446805,
  "transport",
  "packet_received",
  {
    "packet_type": "1rtt",
    "header": {
      "packet_size": 29,
      "packet_number": 5,
      "dcid": "46d3e6a2be3761fd",
      "quic_bit": 0
    },
    "frames": [
      {
        "frame_type": "ping"
      }
    ],
    "type": "1rtt"
  }
]
```

The only other potential problem here is that picoquic uses numbers for packet numbers rather than decimal strings.  Maybe a little tolerance is in order.

Note that you need to set the offset to about -1597611236589 as the two use a different epoch (is there a fixed epoch in the spec?) and #28 causes the default to be incorrect.

**Comment by martinthomson** [comment]
Note that this shows some matches even with the difference in type for packet numbers.

**Comment by rmarx** [comment]
Thank you for finding this bug @martinthomson. 

This was eventually relatively simple. As you observe, there was an issue with upper vs lowercasing in the RTT part of the packet_type field (which meant it did just work for initial and handshake etc.). This goes back to earlier versions of qlog that had different definitions for these things. Similarly with type vs packet_type. When loading an older style qlog file, I try to automatically upgrade it to the newest version and this seems to have slipped between the mazes. 

#28 is potentially a bit more difficult to fix... will comment further there. 

This update should be live within say an hour on the qvis tools website
