### ISSUE TITLE
Extracting qlog files from Firefox

### ISSUE THREAD

**Issue by chanh1964** [quiclog/qvis#68]
Hi all. I've been trying to extract the qlog files from Firefox following your articles and blogs. But until now, I still cannot do it.

For the server-side, I used [quic-go v0.28](https://github.com/lucas-clemente/quic-go) (the latest release at the time I post this). I was able to acquire the qlog files from the server. But when using qvis, I can only get the information up to the QUIC layer. I cannot get information regarding the HTTP/3 layer (e.g., GET requests, type of frames, etc.)

So I started to think maybe if I get the qlog files from the client-side, I could get the HTTP/3 information? I then followed the description in [your article](https://www.smashingmagazine.com/2021/09/http3-practical-deployment-options-part3/):
- Set the `network.http.http3.enable_qlog` in Firefox via `about:config`
- Trigger the QLOGDIR environment variable via terminal:
```bash 
export QLOGDIR=$HOME/Desktop
```

But I don't know why it failed to return any qlog file.
Do you have any idea?

Thank you very much in advance.

**Comment by rmarx** [comment]
Hey there @chanh1964,

Seems like my article isn't entirely correct/clear here, I'm sorry about that...

Firefox does not support QLOGDIR, but instead makes its own directory based on the firefox process ID in the Operating System's temporary directory.

For example, on my Windows system, this is where I could find the qlogs after enabling the `network.http.http3.enable_qlog` pref:

![2022-07-06 15_33_27-Window](https://user-images.githubusercontent.com/2240689/177562450-fb3a24ff-bc2a-4723-810c-1604d6b4323b.png)

The `qlog_` suffix will change depending on your firefox instance. And of course the location will be different on linux/mac. But the qlogs seem to be somewhat usable and are written fast enough (you don't need to close firefox or actively wait for the connections to close or anything).

This is consistent with the code from the original commit adding the qlog preference:
https://hg.mozilla.org/integration/autoland/rev/b53e9a8ffb1f#l4.30

Finally, with regards to HTTP/3, I'm afraid only a few stacks really implement qlog for HTTP/3... it looks like that's not in the Firefox qlogs either; they also only do QUIC. The ones I know about that do H3 logging are Cloudflare's quiche and the Python aioquic library, so maybe you can look into those if that's really what you need (though they also don't log _everything_)?

If you have any more questions, please let me know!

With best regards,
Robin

**Comment by chanh1964** [comment]
Hi @rmarx,

I think you have answered all my questions.
Thank you very much.

Best regards,
Chanh
