### ISSUE TITLE
qvis.quictools.info returning 500

### ISSUE THREAD

**Issue by mxinden** [quiclog/qvis#80]
**Describe the bug**
https://qvis.quictools.info/ is returning 500s to me today.

**To Reproduce**

```
curl https://qvis.quictools.info/  

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
The proxy server could not handle the request<p>Reason: <strong>Error during SSL Handshake with remote server</strong></p><p />
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at qvis.quictools.info Port 443</address>
</body></html>
```

**Expected behavior**

**Screenshots**

**Additional context**
Tested with various online is-it-online tools, curl, Firefox on Ubuntu, Chromium on Ubuntu and Firefox on Android.

**Comment by rmarx** [comment]
Hey there @mxinden,

sorry about that. Should be fixed now! Thanks for reporting :)

**Comment by mxinden** [comment]
:wave: Hi Robin,

Great. Thank you for handling this so quickly. I didn't mean to rush.

Stating the obvious: Qvis and qlog are very helpful. Thank you @rmarx!
